# Generated by Django 4.2.6 on 2023-11-30 16:24

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, blank=False)),
                ('description', models.TextField(max_length=120, blank=True)),
                ('quantity', models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])),
            ],
        ),
    ]
